name: manual-deploy-dummy

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show current datetime
        env:
          TZ: 'Asia/Tokyo'
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Dummy deploy
        run: echo "branch=${GITHUB_REF#refs/heads/}, githash=$(git rev-parse --short HEAD), tag=${{ github.event.inputs.tag }}"
