name: manual-deploy

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: comment
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print log
        run: echo "branch=${GITHUB_REF#refs/heads/}, comment=${{ github.event.inputs.comment }}"
