name: manual-deploy

on: 
  workflow_dispatch:
    inputs:
      comment:
        description: comment
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: print log
        run: echo "branch=${GITHUB_REF#refs/heads/}, githash=$(git rev-parse --short HEAD), comment=${{ github.event.inputs.comment }}"
