name: schedule-action

on:
  schedule:
    - cron: "0 0 * * *" # JST: 09:00 (※時間通りに来ないので注意)

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show current datetime
        env:
          TZ: 'Asia/Tokyo'
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')"
      - name: print log
        run: echo "branch=${GITHUB_REF#refs/heads/}, githash=$(git rev-parse --short HEAD)"
