name: schedule-action

on:
  schedule:
    - cron: "0 9 * * *" # JST: 18:00

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: print log
        run: echo "branch=${GITHUB_REF#refs/heads/}, githash=$(git rev-parse --short HEAD)"
